### ISSUE TITLE
Kotlin Samples

### ISSUE THREAD

**Issue by JIceberg** [FTCLib/FTCLib#106]
**Is your feature request related to a problem? Please describe.**
Yes, there is a distinct lack of samples for some things. It needs samples of the kotlin extensions, as an example.

**Describe the solution you'd like**
@JarnaChao09 Make a few samples utilizing the kotlin extensions. Make sure to test these samples. Also add unit testing (if needed) for some of these extensions.

**Describe alternatives you've considered**
There are none.

**Additional context**
N/A

**Comment by JarnaChao09** [comment]
I can for sure add examples to the samples section. I don't believe unit tests are needed, since it is really not using any new methods. It's just adding convince methods for existing methods that the Kotlin 2 Java interpreter didn't pick up on (mainly due to semantics used)

**Comment by JIceberg** [comment]
> I don't believe unit tests are needed, since it is really not using any new methods. It's just adding convince methods for existing methods that the Kotlin 2 Java interpreter didn't pick up on (mainly due to semantics used).
Makes sense.
