### ISSUE TITLE
AnubhavParida (PIDFController.reset() on a null obj reference)

### ISSUE THREAD

**Issue by 24parida** [FTCLib/FTCLib#112]
**Describe the bug**
when I run this class the error says (in summary) PIDFController.reset() on a null obj reference

**To Reproduce**
create a class called: ShooterTest

copy paste this code: (change package as needed)

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. We would recommend telling us yout:
* OS and version
* Android Studio version
* JDK version

**Comment by 24parida** [comment]
package org.firstinspires.ftc.teamcode;

import com.arcrobotics.ftclib.hardware.motors.Motor;
import com.arcrobotics.ftclib.hardware.motors.MotorEx;
import com.qualcomm.robotcore.eventloop.opmode.Disabled;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;

import java.lang.annotation.Documented;

//shooter test is a class to run the shooter motor with encoders in order to keep velocity constant
@TeleOp(name="Shooter Test", group="Tests")
public class ShooterTest extends LinearOpMode{

    private MotorEx shooterRight;
    private MotorEx shooterLeft;
    public static final double WHEEL_DIAMETER = 4.0;
    public static final double TICKS_PER_REV = 28;


    private static final double TICKS_TO_INCHES = Math.PI * WHEEL_DIAMETER / TICKS_PER_REV;


    @Override
    public void runOpMode() throws InterruptedException {
        shooterRight = new MotorEx(hardwareMap, "shootingMotorRight");
        shooterLeft = new MotorEx(hardwareMap, "shootingMotorLeft");

        //RUN_USING_ENCODER
        shooterLeft.setRunMode(Motor.RunMode.VelocityControl);
        shooterRight.setRunMode(Motor.RunMode.VelocityControl);


        //shooter motor deceleration

        //encoder ticks/inches
        shooterRight.setDistancePerPulse(TICKS_TO_INCHES);
        shooterLeft.setDistancePerPulse(TICKS_TO_INCHES);

        waitForStart();

        while (opModeIsActive()) {
            //5202 1:1 motor || ticks per rev * rpm * seconds / minute * percentage
            shooterLeft.setVelocity(28 * 5000 * 1/60 * 0.9);
            shooterRight.setVelocity(0);


        }
    }
}

**Comment by JIceberg** [comment]
I formatted your code a bit to look nice xd
I will take a look at this. Thanks for the issue.

**Comment by JIceberg** [comment]
# INITIAL BUG REVIEW
Saving the error here for later use - **I did not reproduce it**; this is a screenshot from Discord provided by the author of this issue.
![image](https://cdn.discordapp.com/attachments/674066771904430100/774061903482716170/image0.jpg)

## Report

### Known Qualifiers
* Bug Status: Null Pointer Exception thrown on call `.reset()` for `PIDFController`
* Achieved By: _Unknown_
* Exception Line: _Unknown_
* User Debug Process: _Unknown_

## Related FTCLib Internals

### Instantiation
![image](https://user-images.githubusercontent.com/17654209/98322123-b10e2280-1fb4-11eb-92bc-216aee9cce0c.png)

### Set RunMode
![image](https://user-images.githubusercontent.com/17654209/98322349-2f6ac480-1fb5-11eb-8fdf-3fd2ae5c13f5.png)

**Note**: The PIDFController calls `reset()` in the constructor as well.

### PIDFController
![image](https://user-images.githubusercontent.com/17654209/98322803-4cec5e00-1fb6-11eb-9321-5186672f7875.png)

## Working Code Sample
```java
@TeleOp(name="MotorEx testing")
public class MotorExTest extends LinearOpMode {

    private MotorEx test;

    @Override
    public void runOpMode() throws InterruptedException {
        test = new MotorEx(hardwareMap, "test", GoBILDA.RPM_312);
        test.setRunMode(Motor.RunMode.VelocityControl);
        waitForStart();
        while (opModeIsActive()) {
            if (gamepad1.a) test.setVelocity(312.0 / 60 * 537.6 * 0.9);
            else test.setVelocity(0);
        }
        test.setVelocity(0);
    }

}
```

----
## Initial Correspondence

@24parida Have you tried restarting the app/shutting down the phone? I'd also like you to add a try-catch around the `.setRunMode()` method calls and catch the NullPointerException. Inside of the catch statement, print to telemetry some message. Then, try doing `.set()`. One thing you should note is that setting the runmode here is unnecessary for velocity control if you are using `MotorEx.setVelocity()`.
