### ISSUE TITLE
Conform with WPILib license

### ISSUE THREAD

**Issue by abhaybd** [FTCLib/FTCLib#122]
I could be wrong, but this project uses a substantial amount of files from wpilib but I don't think it properly conforms to the requirements listed in the [project license](https://github.com/wpilibsuite/allwpilib/blob/master/LICENSE.md), since the conditions and disclaimer are not redistributed.

I'm not sure what the fix would be. Maybe include their license in the license for this project?

**Comment by JIceberg** [comment]
Perhaps, but we've never actually heard anything from WPILib folks after multiple correspondences. Would be better to be safe than sorry. I think copying the license and adding a link to WPILib would work best. Each of our files that were copied have the copyright disclaimer in the header.
