### ISSUE TITLE
The Detector Only Returns ZERO for the height of the ring stack

### ISSUE THREAD

**Issue by KeshavVarad** [FTCLib/FTCLib#175]
The getHeight() function only returns ZERO to the program.

**Screenshots**
![image](https://user-images.githubusercontent.com/59457113/105780705-0e27cd80-5f3f-11eb-8457-315aa24f2060.png)

**Comment by JarnaChao09** [comment]
This is a known issue with the current detector, it will be fixed as soon as 1.2.0 is released. If you really need the detector, please copy from the dev branch or just use the pipeline directly.

**Comment by serivesmejia** [comment]
The detector in 1.1.0 wasn’t meant to be used, it only serves as an “example” (kinda broken ngl) of how you would implement your own. That’s going to change in 1.2.0 though, for now just use the pipeline directly.

**Comment by KeshavVarad** [comment]
Thank you!
