### ISSUE TITLE
Command Scheduler Examples

### ISSUE THREAD

**Issue by Cheeseboy8020** [FTCLib/FTCLib#198]
Add examples for the Command Scheduler.

**Comment by JIceberg** [comment]
I'm not sure what you mean here? Why are you trying to use the `CommandScheduler` itself? The purpose of the already built command-based paradigm is to have it so you don't need to call directly to the scheduler.

**Comment by Cheeseboy8020** [comment]
An example on how to run a command in autonomous

**Comment by JIceberg** [comment]
Have you read the [documentation](https://docs.ftclib.org/ftclib/command-base/command-system)? The docs explain how commands can get run. There's no difference between how they are run in autonomous and teleop. Regarding limited samples, we're currently working on expanding the number of samples into its own library: https://github.com/FTCLib/command-based-samples.

**Comment by Cheeseboy8020** [comment]
OK Thanks. I understood how to run/use the commands.
