### ISSUE TITLE
CommandBase.getName() doesn't function as intended

### ISSUE THREAD

**Issue by D3rpyDolphin** [FTCLib/FTCLib#223]
The getter doesn't return m_name which may be chosen by the user, but instead returns the classes simple name as shown below.

![image](https://user-images.githubusercontent.com/20031686/204081414-8691e0b8-deda-4216-85f2-a780818d4efc.png)

This is for version 2.0.1 of FTCLib.

**Comment by foehammer127** [comment]
This issue is resolved
