### ISSUE TITLE
Hello World end-to-end Sample

### ISSUE THREAD

**Issue by baqwas** [FTCLib/FTCLib#225]
**Is your feature request related to a problem? Please describe.**
Based on the information at:

- [https://docs.ftclib.org/ftclib/additional-reading](https://docs.ftclib.org/ftclib/additional-reading)
- [https://docs.ftclib.org/ftclib/installation](https://docs.ftclib.org/ftclib/installation)

I tried to to build the Servo example for a Claw (two servo motors instead of the single in the example - no issue with this specific code). I ran afoul of the  following import statement:

`import com.arcrobotics.ftclib2.command.SubsystemBase;`

**Describe the solution you'd like**
Would like to build a simple exercise _a la_ Hello World to ensure that I am able to use WPILib.

**Describe alternatives you've considered**
- Viewed all the gradle files for any reference to **arcrobotics**
- Browsed some of the text files in this repository for an example or two

**Additional context**
There are thousands of others who are productively using WPILib. I sincerely appreciate the library offerings but I've stumbled at the starting block owing to my ignorance even after starting with a clone of the repository.

I know that I should undertake more Android Studio (and perhaps Java) training but there is so much to learn and so little time...

Thanks for your understanding.

Regards.

**Comment by 1pYDca4d5TUYfb** [comment]
remove the '2' from import com.arcrobotics.ftclib2.command.SubsystemBase;

**Comment by baqwas** [comment]
Thanks! It worked (and I feel embarrassed to say politely!). My excuse is my senility (and POAG). I will let loose WPILib onto our Programming team now.

Kind regards.
