### ISSUE TITLE
TriggerReader Threshold parameter

### ISSUE THREAD

**Issue by Powercube7** [FTCLib/FTCLib#229]
I'm new to this library. After scrolling through the documentation, I realized that the library misses this feature, which I find pretty commonly used.

## Describe the solution you'd like
Add parameter: TriggerReader threshold.

**I am willing to contribute and help with implementing this feature.**

**Comment by Powercube7** [comment]
Feature added in pull request #230

**Comment by JIceberg** [comment]
Good idea, I like it. I'll review it after I publish the new version tonight.
