### ISSUE TITLE
MotorEncoder.getCorrectedVelocity using veloEstimate which isnt set in future call to getRawVelocity

### ISSUE THREAD

**Issue by ericbalsa** [FTCLib/FTCLib#243]
Hi there - hope this makes sense. 

the call stack looks like:

....
my_motor.setVelocity()
MotorEx.setVelocity()
MotorEx.set()     // runMode is set to Velocity
Motor.getCorrectedVelocity() --- the return is used in the PID calculate() 
MotorEncoder.getCorrectedVelocity()

Inside MotorEncoder.getCorrectedVelocity() the code is looking at .veloEstimate but that is only set in getPosition() not in getRawVelocity()

This doesn't manifest itself initially since it's initialized to zero but subsequent runs and the PID starts to get all out of whack because correctedVelocity is returning nonsense (which is used in PID.calculate())

I believe the fix is s/veloEstimate/lastVelo/ inside Encoder.getCorrectedVelocity()

**Comment by JIceberg** [comment]
Great find! I will take care of this and it will be added in the next patch.

**Comment by ericbalsa** [comment]
I can cut a PR if it's easier for you.

**Comment by JIceberg** [comment]
Sure thing! If you're willing. 😄
