### ISSUE TITLE
Docs: Write docs for package com.arcrobotics.ftclib.gamepad

### ISSUE THREAD

**Issue by pranavavva** [FTCLib/FTCLib#35]
Need to write javadocs for the following classes in package `com.arcrobotics.ftclib.gamepad`.
- [x] `ButtonReader`
- [x] `GamepadEx`
- [x] `GamepadKeys`
- [x] `KeyReader`
- [x] `ToggleButtonReader`
- [x] `TriggerReader`

**Comment by pranavavva** [comment]
haven't forgotten about this, it's just that I needed to completely rewrite my team's code

**Comment by JIceberg** [comment]
I can do it.

**Comment by pranavavva** [comment]
oh. thanks :)
