### ISSUE TITLE
Docs: Add Command-Based Autonomous Samples

### ISSUE THREAD

**Issue by codeNinjaDev** [FTCLib/FTCLib#4]
Write a few sample command based autonomous programs in project form instead of the conventional one file sample. Should include a subsystem (probably drive). Will need to updated if we get a new gamepad wrapper.

**Comment by codeNinjaDev** [comment]
Merged sample. Wondering if I need more documentation for it though.

**Comment by JIceberg** [comment]
Finished kekw
