### ISSUE TITLE
Add support for init configuration in auto

### ISSUE THREAD

**Issue by AlexejheroYTB** [FTCLib/FTCLib#50]
After init, but before randomization, Gamepad input can be used alongside Telemetry in order to simulate a text-based interface to configure the autonomous.

This could be added into the library, and be called via a `addOption` method, and the configuration be accessed via a `getOption` method or an `options` array.

I already have the code for this. If you think this would be a good addition to this library, I'd happily make a PR.

**Comment by codeNinjaDev** [comment]
I definitely think it would be a great addition and would love a PR!

**Comment by AlexejheroYTB** [comment]
I am not very familiar with the codebase of this library.
* Where would be a good place to put it? Maybe in an OpMode super class? (It needs an init_loop hook)
* How should options be added and accessed? The signature I use for the add method is `addOption(String name, String[] values, [int default])`, and to access options  I use `int[] options` in the base OpMode class, the values being the indices of the selected options.
* What should happen if the startup of the OpMode is attempted before all of the non-default options are selected? Currently I have it setup that it will requestOpModeStop, but other stuff can be done as well, such as forcing a default value.

**Comment by codeNinjaDev** [comment]
We have a commandOpMode super class that we could put it in. I feel like forcing a default value is a more robust solution as well as an ArrayList instead of an actual array.

**Comment by Lunerwalker2** [comment]
Maybe have a disabled parameter that is checked at init before the options are populated. That way if you aren't using them they won't effect a quick start up of the opmode. Maybe something like `setDisabled(true)`

**Comment by AlexejheroYTB** [comment]
ArrayList<String> with the values of the options or ArrayList<Integer> with their indices?

Also, instead of forcing a default value, a default value could be `-1` or `""`, but that may pose an issue if the developer doesn't account for it.

**Comment by AlexejheroYTB** [comment]
More details will be discussed in the PR
