### ISSUE TITLE
Getting "libOprnCvNative.so was not found, any OpenCV-enabled OpModes will crash..."

### ISSUE THREAD

**Issue by foocross** [FTCLib/FTCLib#70]
**Describe the bug**
When the we added FTCLib to our skystone code, we got the error. We have previously copied over libOpenCVNative.so to the phone and we checked it is still there.

**To Reproduce**
Installed FTCLib per the instructions (verison 0.0.0)

**Expected behavior**
We should not get the error

**Additional context**
Add any other context about the problem here. We would recommend telling us:
* OS and version - 8.0.0 (moto e)
* Android Studio version - 4.0
* JDK version - 1.8

**Comment by JIceberg** [comment]
Hello! Have you read the README for the EasyOpenCV repository and recopied the native file to the phone?

**Comment by Jaiming724** [comment]
Can you send a picture of where libOpenCvNative.so is located?

**Comment by foocross** [comment]
Sorry for the delay- we had to grab the robot.
![error](https://user-images.githubusercontent.com/53792056/89105233-67c69980-d3ed-11ea-877a-80cb23bb2d07.jpg)
![file-list](https://user-images.githubusercontent.com/53792056/89105235-6a28f380-d3ed-11ea-97d3-f7915c6cfa2b.jpg)

**Comment by foocross** [comment]
I should have said that this is on the new REV control hub

**Comment by Jaiming724** [comment]
Ah that explains alot. This issue is caused by the app running 64 bit. To solve this, go to your build.common.gradle and remove any instances of arm64-v8a you see.

**Comment by foocross** [comment]
Ah thanks- that worked. How did you know it was running 64 bit?

**Comment by Jaiming724** [comment]
It is just something the control hub does.

**Comment by Jaiming724** [comment]
To elaborate, both the phones and the control hub uses 64 bit chips. But the phones use 32 bit software. Because rev makes control hubs themselves, they decided to have it run 64 bit.

**Comment by foocross** [comment]
Never knew that- thanks.
