### ISSUE TITLE
Documentation how to use Path inside purepursuit

### ISSUE THREAD

**Issue by foocross** [FTCLib/FTCLib#73]
**Is your feature request related to a problem? Please describe.**
Some clear documentation on how to use Path, particularly Path.loop in side purepursuit without using much of FTCLib

**Describe the solution you'd like**
Some documentation on how to use class. 

**Additional context**
Based on code, it seems:
path = new Path(new StartWaypoint(0,0),new GeneralWaypoint(200,0,0.8,0.8,1), new EndWaypoint());

double[] motorPowers = path.loop(robot.returnXCoordinate(), robot.returnYCoordinate(), robot.returnOrientation());

should work. But powers all come back as {nan,nan,0}

**Comment by JIceberg** [comment]
How are you handling the robot odometry? Are you updating the pose after every iteration of the loop? Did you put the `loop()` method into some sort of iterator?

**Comment by JIceberg** [comment]
The way you are calling the method is correct.. I am not sure why it is returning that as a result.

**Comment by JIceberg** [comment]
Moreover, an alternative method is just calling the `followPath()` method instead of doing everything yourself.

**Comment by foocross** [comment]
We are calculating the positions directly based on the tutorial from wizards.exe. We want to test FTCLib and wrote a simple loop:

        while(!path.isFinished() && opModeIsActive()) {
                // Get the robot's current position using the odometry.
                double[] motorPowers = path.loop(robot.returnXCoordinate(), robot.returnYCoordinate(), robot.returnOrientation());
                // Update motor speeds.
                telemetry.addData("x power",motorPowers[0]);
                telemetry.addData("Y power",motorPowers[1]);
                telemetry.addData("angle power",motorPowers[2]);
                telemetry.update();
    }

**Comment by JIceberg** [comment]
Just as a heads up: you need to call the init method before calling the `loop()` method. I'm sure that is before your loop though. Make sure to call `.isLegalPath()` to see if your path is legal.

**Comment by foocross** [comment]
I thought init called .isLegalPath(). Our code is: Is there a bug?

       path = new Path(new StartWaypoint(0,0),new GeneralWaypoint(200,0,0.8,0.8,1), new EndWaypoint());
        path.init();
        waitForStart();
        robot.start();
        Log.d("testTag","START TestAuto");

        displayPosition();

        while(!path.isFinished() && opModeIsActive()) {
                // Get the robot's current position using the odometry.
                double[] motorPowers = path.loop(robot.returnXCoordinate(), robot.returnYCoordinate(), robot.returnOrientation());
                // Update motor speeds.
                telemetry.addData("x power",motorPowers[0]);
                telemetry.addData("Y power",motorPowers[1]);
                telemetry.addData("angle power",motorPowers[2]);
                telemetry.update();
        }

**Comment by JIceberg** [comment]
I ran this test and had `motorPowers` return `{1, 0, 0}`. I would try printing the values to the logcat instead of telemetry in case there is an issue there.

**Comment by JIceberg** [comment]
I would also log the calls to the `robot` object to make sure those methods aren't returning NaN.

**Comment by puravdatta-sudo** [comment]
I would log the actual dt power outputs and work backwards, essentially make sure that it is getting an input and trace backwards.

**Comment by foocross** [comment]
> I ran this test and had `motorPowers` return `{1, 0, 0}`. I would try printing the values to the logcat instead of telemetry in case there is an issue there.

Do you mind posting your code? It is probably user error :)

**Comment by JIceberg** [comment]
I copied your path and ran it through a general math test. I then assumed your initial position was `(0,0,0)` on the robot.
```java
path = new Path(new StartWaypoint(0,0),new GeneralWaypoint(200,0,0.8,0.8,1), new EndWaypoint());
path.init();
double[] motorPowers = path.loop(0, 0, 0);

// log the speeds
Log.d("Horizontal Speed", "Value: " + Double.toString(motorPowers[0]));
Log.d("Vertical Speed", "Value: " + Double.toString(motorPowers[1]));
Log.d("Turn Speed", "Value: " + Double.toString(motorPowers[2]));
}
```

**Comment by Volt40** [comment]
Hi, sorry for taking so long to get to this. The issue is with this line:
`path = new Path(new StartWaypoint(0,0),new GeneralWaypoint(200,0,0.8,0.8,1), new EndWaypoint());`
When you create an EndWaypoint, you should give it some parameters. The blank constructors should only be used if you plan on setting the waypoint's values later, otherwise they bug out.
Try something like this:
`path = new Path(new StartWaypoint(0,0),new GeneralWaypoint(200,0,0.8,0.8,30), new EndWaypoint(400, 0, 0, 0.5, 0.5, 30, 0.8, 1));`
After you get the robot moving, make sure to play around with the motion profiles and fine tune the waypoint settings to get it smooth.

**Comment by foocross** [comment]
thanks @Volt40 that worked
