### ISSUE TITLE
Pure Pursuit: Skews to the right on start

### ISSUE THREAD

**Issue by smartynenko** [FTCLib/FTCLib#77]
Hi, I am trying new Pure Pursuit library and need some guidance on proper parameters to describe the path. It seem no matter of how I configure my path robot always strafes to the right on startup and than continues oscillating around the path

        SimpleMotorEx fL = new SimpleMotorEx("frontLeft", hardwareMap, 435);
        SimpleMotorEx fR = new SimpleMotorEx("frontRight", hardwareMap, 435);
        SimpleMotorEx bL = new SimpleMotorEx("backLeft", hardwareMap, 435);
        SimpleMotorEx bR = new SimpleMotorEx("backRight", hardwareMap, 435);

        bL.setInverted(true);
        fL.setInverted(true);

        MecanumDrive dt = new MecanumDrive(false, fL, fR, bL, bR);

        waitForStart();

        if (isStopRequested()) return;
        double movSpeed = .8;
        double turnSpeed = 1;

        // With X and Y coordinates.
        Waypoint p1 = new StartWaypoint(0, 0);
        Waypoint p5 = new EndWaypoint(65, 0, 0, movSpeed, turnSpeed, 5, 5, .5);

        // we are using the waypoints we made in the above examples
        Path m_path = new Path(p1, p5);
        m_path.init(); // initialize the path

        if (opModeIsActive()) {
            while (!m_path.isFinished() && opModeIsActive()) {
                if (m_path.timedOut())
                    throw new InterruptedException("Timed out");

                localizer.update();
                Pose2d currentPose = localizer.getPoseEstimate();

                // return the motor speeds
                double speeds[] = m_path.loop(currentPose.getX(), currentPose.getY(), currentPose.getHeading());
                dt.driveRobotCentric(speeds[0], speeds[1], speeds[2]);

            }

            dt.stop();
        }

![image](https://user-images.githubusercontent.com/50431171/90940812-21f26500-e3de-11ea-9def-325d43fabcd4.png)

**Comment by JIceberg** [comment]
What is this `localizer` object you have in your OpMode? I don't see a definition for it, so I don't know how you are estimating your robot's pose. Do you mind elaborating on that?

**Comment by smartynenko** [comment]
it is VSLAM+gyro based. In case if localizer is a culprit, what part should I pay attention to?

![image](https://user-images.githubusercontent.com/50431171/90993661-b3e7a280-e583-11ea-975d-7a0af7e94f37.png)

**Comment by JIceberg** [comment]
Ah I see the issue. Pure pursuit says `x` is the horizontal movement and `y` is the vertical. Based on the image you provided, I believe this might be the cause.

**Comment by smartynenko** [comment]
Ok, thank you. I will try with different config
