### ISSUE TITLE
Field orientation not working in driveFieldCentric

### ISSUE THREAD

**Issue by foocross** [FTCLib/FTCLib#79]
**Describe the bug**
In MecanumDrive method driveFieldCentric- it seems to ignore the field orientation from the gyro.

public void driveFieldCentric(double xSpeed, double ySpeed,
                                  double turnSpeed, double gyroAngle) {
        xSpeed = clipRange(xSpeed);
        ySpeed = clipRange(ySpeed);
        turnSpeed = clipRange(turnSpeed);

        Vector2d input = new Vector2d(xSpeed, ySpeed);
        input = input.rotateBy(-gyroAngle);

        double theta = Math.atan2(ySpeed, xSpeed);

        double[] wheelSpeeds = new double[4];
        wheelSpeeds[MotorType.kFrontLeft.value] =
                input.magnitude() * Math.sin(theta + Math.PI / 4) + turnSpeed;
        wheelSpeeds[MotorType.kFrontRight.value] =
                input.magnitude() * Math.sin(theta - Math.PI / 4) - turnSpeed;
        wheelSpeeds[MotorType.kBackLeft.value] =
                input.magnitude() * Math.sin(theta - Math.PI / 4) + turnSpeed;
        wheelSpeeds[MotorType.kBackRight.value] =
                input.magnitude() * Math.sin(theta + Math.PI / 4) - turnSpeed;

The theta ignores the new angel from input. We believe theta should be something like:

        double theta = Math.atan2( input.getY(),  input.getX());

**Additional context**
Add any other context about the problem here. We would recommend telling us yout:
version 1.0.0 of FTClib

**Comment by JIceberg** [comment]
Changed the code to:
```java
double theta = input.angle();
```
Resolved in v1.0.1, please update your maven and let us know if it works.

**Comment by foocross** [comment]
It worked - but we found another problem. We don't know how to fix it- but will open an issue.
